//
// VortexBannerAnimationView.h
// Generated by Core Animator version 1.3 on 8/20/16.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface VortexBannerAnimationView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// VortexBannerAnimation
- (void)addVortexBannerAnimation;
- (void)addVortexBannerAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addVortexBannerAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)removeVortexBannerAnimation;

- (void)removeAllAnimations;

@end