//
// VortexPageAnimationView.h
// Generated by Core Animator version 1.3 on 8/21/16.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface VortexPageAnimationView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// vortex page animation
- (void)addVortexPageAnimation;
- (void)addVortexPageAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addVortexPageAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)removeVortexPageAnimation;

- (void)removeAllAnimations;

@end